### ISSUE TITLE
Template: Add ability to have 2 signature blocks

### ISSUE THREAD

**Issue by mvandenbos** [mvandenbos/steuerbescheinigungen-spender#3]
Some churches require the Cashier to also sign the documents and it would be good to have an additional signature block

**Comment by koehdaniel** [comment]
Since there is not enough space in one line for two signatures, I moved the signatures 2 lines down, but only if there is a cashier to sign.

Without cashier it is still in the same line with the City and Date:

![image](https://user-images.githubusercontent.com/57719249/69747665-7a4a4e00-114f-11ea-92e2-b1d7642ef5bc.png)

But with a cashier everything is moved 2 lines down:

![image](https://user-images.githubusercontent.com/57719249/69747721-951cc280-114f-11ea-8494-52d548940635.png)

**Comment by koehdaniel** [comment]
https://github.com/koehdaniel/steuerbescheinigungen-spender/commit/c906da5c97d048c9e38021e15f865460d647b2d4

The TemplateView during editing the Template still needs to be adapted.

**Comment by koehdaniel** [comment]
You squeezed the second signature in the same line as the City and Date, which is not enough space for our Church-Name, which results in a line-break:
![image](https://user-images.githubusercontent.com/57719249/70920837-e112a700-202b-11ea-8895-a4ecb22030da.png)


Furthermore there is a random " 1" after the Church-Name.

You didn't like moving down the signatures? 
But I don't see any other posibility here due to the limited width of the page.

**Comment by mvandenbos** [comment]
`You didn't like moving down the signatures?`
Not really, I didn't find it correct that a signature had to be signed over the date.  I'll play around with this a bit more and come up with a solution that better incorporates longer church names.  

I appreciate you testing this and reporting it back to me.

The "1" was a test that I accidentally didn't remove... since the same church name was used for both signatures I wanted to make sure which one I was working with while formatting the document.  I'll get that removed.

**Comment by mvandenbos** [comment]
I was thinking of removing the Church Name from the signature block and adding 2 new lines that users can fill as needed.  

That way, if a different signature text is required the users can do that, or in cases like with your church, you would then be able to define where you want to split the text.  

What is your opinion on that option?

**Comment by mvandenbos** [comment]
This is also an option:
![image](https://user-images.githubusercontent.com/57481723/70945604-d967f800-2055-11ea-910d-d2cc51f22430.png)

**Comment by koehdaniel** [comment]
I don't like the Idea of splitting the Churchname to multiple lines.
We don't really need the Churchname at all, so putting a customizable line which can be filled as needed, would be totally fine for us.
